### ISSUE TITLE
После скачивания 3.0 не инжектит

### ISSUE THREAD

**Issue by ListerStellar** [clangremlini/fet-loader#13]
Скачал версию 3.0 и при инжекте сторонней длл качает какой то файл под названием VCRHyb64.exe и ничего не инжектит. Открыл файл, установилось и всё та же картина, тупо качает этот файл по новой и не инжектит. Как решить?

**Comment by clownless** [comment]
предостаь логи %appdata%\FET Loader\logs.log

**Comment by ListerStellar** [comment]
[logs.log](https://github.com/clangremlini/fet-loader/files/5709010/logs.log)
Я потом скачал старую версию, и если в папке с лоудером дллку переименовать в "ERROR" то если выбрать "custom" то дллка инжектиться, так заинжектил зара 3 чит, надеюсь не повлияет на логи

**Comment by clownless** [comment]
https://github.com/clangremlini/fet-loader/releases/tag/v3.0.1
Исправлено
