### ISSUE TITLE
Colors 2.0

### ISSUE THREAD

**Issue by g42ftw** [clangremlini/fet-loader#16]
I've attached 3 files with better colors, 1 new theme, fixed shadows and bold focus lines etc.
[colors2.zip](https://github.com/clangremlini/fet-loader/files/5898503/colors2.zip)

**Comment by clownless** [comment]
@g42ftw почему два раза

**Comment by g42ftw** [comment]
> @g42ftw почему два раза
Всё как у людей

**Comment by clownless** [comment]
Soon
