### ISSUE TITLE
Добавьте возможность смотреть видео на YouTube канале REZOLVER прямо в лоадере!

### ISSUE THREAD

**Issue by 0shnik** [clangremlini/fet-loader#19]
Недавно я увидел концепт от уважаемого @oliyase с внедрением канала REZOLVER прямо в лоадере! Так как чит инжектится очень долго, как и у меня запускается сама CS:GO, я всегда смотрю его видео и я его фанат! Так что я считаю возможность смотреть его видео в лоадере очень полезно и хорошо скоротает время!
<img width="418" alt="Component 1" src="https://user-images.githubusercontent.com/78692735/107150553-60b9ae80-696f-11eb-993c-27f13ceb44ec.png">

**Comment by clownless** [comment]
ПХЫЪЫВХПВЫХЗПВХЫАЗАХЪВЫАХЗЛАПАХЗВЫАЗХВЫЖЗАЫФВАФВЫЭЖЪАЫФЖЗЪХВЫФ

**Comment by oliyase** [comment]
полностью согласен с этим issue

**Comment by rfoxxxy** [comment]
юзлесс закрыто бан гитхаб аккаунта

**Comment by clownless** [comment]
не юзлесс, очень полезная функция! будет реализовано в следующей версии!)

**Comment by oliyase** [comment]
> юзлесс закрыто бан гитхаб аккаунта

да ну, лучшая фича 2012-2025 года!!!!!

**Comment by clownless** [comment]
@oliyase согласен

**Comment by rfoxxxy** [comment]
миксер пошел нахуй

**Comment by clownless** [comment]
> миксер пошел нахуй

завали ебало

**Comment by rfoxxxy** [comment]
я твою матье абл

**Comment by clownless** [comment]
> я твою матье абл

ротяру

**Comment by oliyase** [comment]
@clownless соси копирка фокседа

**Comment by clownless** [comment]
> @clownless соси копирка фокседа

сам такой

**Comment by oliyase** [comment]
@clownless сори я не тебе я хожел рфокседу

**Comment by rfoxxxy** [comment]
отсосите

**Comment by clownless** [comment]
> @clownless сори я не тебе я хожел рфокседу

лан

> отсосите

ору нищ не пук

**Comment by kim1nonawa** [comment]
вообще-то на канале а4

**Comment by clownless** [comment]
> вообще-то на канале а4

согласен

**Comment by clownless** [comment]
@kim1nonawa

**Comment by oliyase** [comment]
го

**Comment by clownless** [comment]
@aliveoutside еблан

**Comment by clownless** [comment]
лень делать идите нахуй

**Comment by kim1nonawa** [comment]
ээй
