### ISSUE TITLE
Its ok?

### ISSUE THREAD

**Issue by Fragrus** [clangremlini/fet-loader#7]
![изображение](https://user-images.githubusercontent.com/26599635/99142685-7a956f00-2668-11eb-8d3c-fe6727ee8a38.png)

**Comment by m4x3r** [comment]
позже фиксану, t.me/ayeahkloader для связи

**Comment by m4x3r** [comment]
@Fragrus дай скриншот winver

**Comment by Fragrus** [comment]
![изображение](https://user-images.githubusercontent.com/26599635/99149679-a2a0c480-26a0-11eb-910b-05d74cc09357.png)

**Comment by rfoxxxy** [comment]
@Fragrus Решение - обновиться на последнюю версию винды. Закрыто.
