### ISSUE TITLE
Чё за бред, чё то kernel что то не так

### ISSUE THREAD

**Issue by ListerStellar** [clangremlini/fet-loader#8]
https://prnt.sc/vnfs26
Бам бом бам бим чича чоча чачи

**Comment by m4x3r** [comment]
> https://prnt.sc/vnfs26
> Бам бом бам бим чича чоча чачи

@ListerStellar дай лог-файл (%AppData%\FET Loader\logs.log)

**Comment by ListerStellar** [comment]
[logs.log](https://github.com/clangremlini/fet-loader/files/5577999/logs.log)
на

**Comment by m4x3r** [comment]
@ListerStellar Сам компилил?)

**Comment by ListerStellar** [comment]
Я увидел файл compile и запустил, но ничего не открылось, а в папке лежал файл loader.ahk Я его запускал

**Comment by m4x3r** [comment]
> Я увидел файл compile и запустил, но ничего не открылось, а в папке лежал файл loader.ahk Я его запускал

а github.com/clangremlini/fet-loader/releases для кого?
надо скачать скомпилированный loader.exe

**Comment by toxyxd** [comment]
> Я увидел файл compile и запустил, но ничего не открылось

Советую почитать README, говорят, полезная вещь
